
var APP_CONSTANTS = {
    DEFAULT_DIRECTORY_PATH: "./",
    DEFAULT_FOLDER_NAME: "xodata",
    DEFAULT_OUTPUT_FOLDER_PATH: "./",
    DEFAULT_OUTPUT_FOLDER: "mockdata",
    DEFAULT_METADATA_URI_PATH: "$metadata"
}
exports.constants = APP_CONSTANTS;